export const IPC_CHANNELS = {
  AGENT_INVOKE: 'agent:invoke',
  AGENT_MESSAGE: 'agent:message',
  AGENT_RESTART: 'agent:restart',
  SHELL_EXECUTE: 'shell:execute',
  UPDATE_PROGRESS: 'update:progress',
  CONFIG_GET: 'config:get',
  CONFIG_SET: 'config:set',
  CONFIG_UPDATE: 'config:update',
  THEME_CHANGE: 'app:theme-change',
  FONT_SCALE_CHANGE: 'app:font-scale-change',
  WINDOW_MINIMIZE: 'window:minimize',
  WINDOW_MAXIMIZE: 'window:maximize',
  WINDOW_CLOSE: 'window:close',

  // 原生对话模式
  NATIVE_INIT_DRIVER: 'native:init-driver',
  NATIVE_GET_HEALTH: 'native:get-health',
  NATIVE_CREATE_SESSION: 'native:create-session',
  NATIVE_OPEN_SESSION: 'native:open-session',
  NATIVE_LIST_SESSIONS: 'native:list-sessions',
  NATIVE_SEND_MESSAGE: 'native:send-message',
  NATIVE_CANCEL_RUN: 'native:cancel-run',
  NATIVE_GET_TRANSCRIPT: 'native:get-transcript',
  NATIVE_GET_SESSION_TREE: 'native:get-session-tree',
  NATIVE_NAVIGATE_TREE: 'native:navigate-tree',
  NATIVE_GET_WORKSPACE_TREE: 'native:get-workspace-tree',
  NATIVE_GET_FILE_PREVIEW: 'native:get-file-preview',
  NATIVE_SELECT_DIRECTORY: 'native:select-directory',
  NATIVE_PATH_EXISTS: 'native:path-exists',
  NATIVE_CLIPBOARD_COPY: 'native:clipboard-copy',
  NATIVE_TOAST: 'native:toast',
  NATIVE_GET_DIFF: 'native:get-diff',
  NATIVE_LIST_MODELS: 'native:list-models',
  NATIVE_SET_MODEL: 'native:set-model',
  NATIVE_LIST_SKILLS: 'native:list-skills',
  NATIVE_INVOKE_SKILL: 'native:invoke-skill',
  NATIVE_DELETE_SESSION: 'native:delete-session',
  NATIVE_SET_SESSION_MODE: 'native:set-session-mode',
  NATIVE_SET_SESSION_CONFIG_OPTION: 'native:set-session-config-option',
  NATIVE_SESSION_EVENT: 'native:session-event',

  MARKETPLACE_LIST_AGENTS: 'marketplace:list-agents',
  MARKETPLACE_UPLOAD_AGENT: 'marketplace:upload-agent',
  MARKETPLACE_GET_CATEGORIES: 'marketplace:get-categories',
} as const;
